local_data_file(): Update XDG file not found error message
The "error" prefix caused a redundant message on the console:

    error: error getting XDG data path